### ISSUE TITLE
Not showing any UI or errors

### ISSUE THREAD

**Issue by voidplayer** [oberien/adb-remote-control#1]
No compilation instructions, but i expected this to work

```
$ pwd
./src/

$ java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)

$ javac de/oberien/adbremotecontrol/Main.java

$ java de.oberien.adbremotecontrol.Main 
Config File not found, falling back to defaults
```

**Comment by oberien** [comment]
Could you please try again with e8522c9 ?

**Comment by voidplayer** [comment]
Same

I was trying to debug it using eclipse, but is taking me awhile to find the problem

btw im using

```
javac **/*.java
```
to compile, because once the .class are generated they arent recompiled even if you change the source on some file that is not ```Main.java```

**Comment by voidplayer** [comment]
it seems to be stucked forever in ```AdbShell.java:11```
```java
readUntil((byte) 0x1b, (byte) 0x37, (byte) 0x1b, (byte) 0x5b, (byte) 0x72, (byte) 0x1b, (byte) 0x5b, (byte) 0x39, (byte) 0x39, (byte) 0x39, (byte) 0x3b, (byte) 0x39, (byte) 0x39, (byte) 0x39, (byte) 0x48, (byte) 0x1b, (byte) 0x5b, (byte) 0x36, (byte) 0x6e, (byte) 0x1b, (byte) 0x38);
```

**Comment by oberien** [comment]
In my linked commit I should have fixed the problem of `readUntil` ending in an infinite loop. For recompilation I use the following command, which will definitely recompile everything:
```sh
rm **/*.class && javac de/oberien/adbremotecontrol/Main.java
```

Could you please tell me if the java process is taking 100% / 200% of your CPU (i.e. if 1 or 2 cores are fully used)?

**Comment by voidplayer** [comment]
neither

![selection_312](https://user-images.githubusercontent.com/4019910/39549209-501e502e-4e5d-11e8-838c-e04b1a4e8bb5.png)

I was trying to debug it under eclipse. Ive used other debuggers before but never with java

I will try to do it again

**Comment by voidplayer** [comment]
This is the stack when it hangs. It never finish the step over (f6 on eclipse)

AdbProcess.java:39
```java
            int len = in.read(buf);
```

Eclipse have some bug and i cant copy it, but heres a screenshot

![selection_313](https://user-images.githubusercontent.com/4019910/39551674-3a608136-4e66-11e8-8ee4-85c706a839d9.png)

**Comment by oberien** [comment]
I think I have an idea what could be happening here. Could you please give me the output of `echo | adb shell | xxd`?
My guess is that the hardcoded `readUntil` bytes I use do not match yours:
```java
readUntil((byte) 0x1b, (byte) 0x37, (byte) 0x1b, (byte) 0x5b, (byte) 0x72, (byte) 0x1b, (byte) 0x5b, (byte) 0x39, (byte) 0x39, (byte) 0x39, (byte) 0x3b, (byte) 0x39, (byte) 0x39, (byte) 0x39, (byte) 0x48, (byte) 0x1b, (byte) 0x5b, (byte) 0x36, (byte) 0x6e, (byte) 0x1b, (byte) 0x38);
readUntil("shell@jfltexx:/ $ ".getBytes());
```

**Comment by voidplayer** [comment]
``` echo |adb shell|xxd ``` returned empty and exited with 0

This is a small output sample of adb shell

```
$ adb shell
tissot:/ $ l
/system/bin/sh: l: not found
127|tissot:/ $ pwd
/
tissot:/ $ cat 
asd
asd
tissot:/ $ cat sdf                                                                                                                           
cat: sdf: No such file or directory
1|tissot:/ $ ^D
```

**Comment by voidplayer** [comment]
and this is the output of ```$ adb shell|xxd```

```
00000000: 7469 7373 6f74 3a2f 2024 205e 440d 0d0a  tissot:/ $ ^D...
```

**Comment by oberien** [comment]
As it seems your device does not send some binary data blob as my S4 does if the shell's output is piped and not stdout. I think the fix here is for you to remove the line with the hardcoded bytes and to exchange the line after (hardcoded for my S4) to your `tissot:/ $ `.

**Comment by oberien** [comment]
Were you able to fix this problem with my suggestion?

**Comment by oberien** [comment]
Closing this due to no response from OP. Also https://github.com/oberien/adb-remote-control/issues/2#issuecomment-487188327 confirms that v0.1.2 is working.
