### ISSUE TITLE
More native PC-like text control characters.

### ISSUE THREAD

**Issue by Sur3** [oberien/adb-remote-control#11]
It would be nice if del, pos1(alias home) and end would work properly like in a normal text editor, meaning del removing the next character following the cursor (keyevent 22 followed by keyevent 67), home jumping to the beginning of a line (500x keyevent 21) and end jumping to the end of the line (500x keyevent 22).
I know home is mapped to the home button, but for typing on a keyboard this is not the normal behaviour when writing text and the home button could be mapped elsewhere (e.g. insert); I mean the back button is also not mapped to backspace but to escape for a good reason.

**Comment by Sur3** [comment]
Also being able to paste text from the PC's clipboard with ctrl+v would be really useful for pasting links and other text.

**Comment by Sur3** [comment]
Also it would be nice to be able to send keyevent 26 when the display is disabled (black screenshot) to enable it, so you don't have to press the power button on the device itself.

**Comment by oberien** [comment]
Thanks for reporting these issues. I think they are very good additions. I'll get back to them in a week or so, when I have more time.

**Comment by Sur3** [comment]
Also right-click could be mapped to long press.

**Comment by oberien** [comment]
> I'll get back to them in a week or so, when I have more time.

Famous last words…

Would you mind creating a PR with your suggested changes? The changes should be rather simple and can be done similar to how Ctrl+d is handled:
https://github.com/oberien/adb-remote-control/blob/3f4d336652e544d26c9d4d9f450e6cd7651d1586/src/de/oberien/adbremotecontrol/view/ScreenPanel.java#L66-L77
One-to-one mappings and the behaviour of `Home` should be done here:
https://github.com/oberien/adb-remote-control/blob/3f4d336652e544d26c9d4d9f450e6cd7651d1586/src/de/oberien/adbremotecontrol/adb/AndroidKeyEvent.java#L111-L115
