### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by padinko** [oberien/adb-remote-control#12]
Hello,
I can't run your app. I only have this error:
```
C:\android\adb-remote-control> C:\android\platform-tools\adb.exe devices
List of devices attached
ZE2224779H      device

C:\android\adb-remote-control> java -jar .\adb-remote-control.jar
Get Screenshot
Exception in thread "main" java.lang.NullPointerException
        at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:23)
        at de.oberien.adbremotecontrol.Main.main(Main.java:7)
```

I have connected device with usb cable and ADB enabled. I use v0.1.3. Java version:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by oberien** [comment]
I can't reproduce this error, but my guess would be that `ImageIO.read` returns `null`. According to its documentation, that can only have one cause: `If no registered ImageReader claims to be able to read the resulting stream, null is returned.`

Therefore I think it might be that `adb.exe shell screencap -p` doesn't produce a correct image. Could you please manually execute that command and check if it produces a valid image? Or at least, if it starts with the three letters `PNG`?

**Comment by padinko** [comment]
it returns some binary file, but before `PNG` is wierd character and windows cant open that image

![image](https://user-images.githubusercontent.com/12599001/82549517-55aebc00-9b5d-11ea-95e2-f1a874937568.png)

**Comment by oberien** [comment]
That actually looks like a fine png header. According to the PNG specification "The first eight bytes of a PNG file always contain the following (decimal) values: 137 80 78 71 13 10 26 10". In extended ASCII, that's `ëPNG\r\n<SUB>\n` which is exactly what is shown in notepad…

Could you please attach that PNG file to a comment in this issue? It must be some other malformatting.

**Comment by padinko** [comment]
image from that command:
![img](https://user-images.githubusercontent.com/12599001/82561773-3b340d00-9b74-11ea-837c-a99fffd64346.png)

I tried [Adb Remote Screen](https://github.com/MajeurAndroid/Adb-Remote-Screen) and it works for me.. but only 1 screen per 2 seconds what is very bad for me

**Comment by oberien** [comment]
As it turns out, you can't run adb-remote-control from PowerShell. PowerShell only sends UTF-16 over stdout / stdin. I'm reading the PNG from the stdout of adb, which means that PowerShell first converts the binary PNG to weird UTF-16, which is not revertible.
Could you please try running it with cmd.exe instead of from PowerShell?

**Comment by padinko** [comment]
i tried `cmd` and `Git Bash`, both same result as PowerShell

**Comment by oberien** [comment]
Could you please try if the [newest version](https://github.com/oberien/adb-remote-control/releases/tag/v0.1.4) works? If not, could you please provide me with the output of `adb shell 'screencap -p | base64 -w 0'` and  `adb shell 'screencap -j | base64 -w 0'`?

**Comment by padinko** [comment]
still same as before

my screencap have no `-j` parameter (it prints help). 
[png.txt](https://github.com/oberien/adb-remote-control/files/4667542/png.txt) is a valid base64, i can convert it to binary and successfully open png 

with default config it will throw same exception as before (probably no jpg option)
with `imageFormat=png` is the result same with `NullPointerException` at (MainFrame.java:23)

**Comment by oberien** [comment]
Could you please try again with [v0.1.5](https://github.com/oberien/adb-remote-control/releases/tag/v0.1.5)?

>  but only 1 screen per 2 seconds what is very bad for me

Unfortunately that's the performance of creating a PNG screenshot and downloading it over adb. Additionally, adding the Base64 hack I implemented for Windows now increases that time again by roughly 33%. That's why I implemented JPG, as it's about 3-4 times as fast.

**Comment by padinko** [comment]
```
C:\android\adb-remote-control> java -jar .\adb-remote-control.jar
Get Screenshot
Switching to Base64-Mode
Exception in thread "main" java.lang.RuntimeException: Invalid image, but we are already using base64
        at de.oberien.adbremotecontrol.adb.AdbDevice.screenshot(AdbDevice.java:39)
        at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:22)
        at de.oberien.adbremotecontrol.Main.main(Main.java:7)
```

**Comment by oberien** [comment]
Lets try this again with [v0.1.6](https://github.com/oberien/adb-remote-control/releases/tag/v0.1.6) :)

**Comment by padinko** [comment]
working thx :)
but as you said performance is not perfect, but for some screen testing is good
