### ISSUE TITLE
Image Error

### ISSUE THREAD

**Issue by Emnolope** [oberien/adb-remote-control#13]
```
Config File not found, falling back to defaults
Get Screenshot
Switching to Base64-Mode
Exception in thread "main" java.lang.RuntimeException: Invalid image, but we are already using base64
        at de.oberien.adbremotecontrol.adb.AdbDevice.screenshot(AdbDevice.java:39)
        at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:22)
        at de.oberien.adbremotecontrol.Main.main(Main.java:7)
```
I'm running the jar file inside of the most recent platform tools folder.

**Comment by oberien** [comment]
1. Which OS are you using?
2. How are you starting the jar file (double-click / from cmd / powershell / git bash / …)?
3. Could you please attach the output of `adb shell screencap -p` and `adb shell screencap -j` as a file?

**Comment by jboyter14** [comment]
I was having the same issue and figured out that my android box that I was connecting to didn't support jpeg which was the default (screencap didn't know what the -j parameter was).
So I added the config.properties file to my platform tools folder where I'm running from and put in one line:
imageFormat=png

Seems to be working great now.  Thanks!!

**Comment by oberien** [comment]
That's what I'm suspecting as well, which is why I asked for those outputs. I should probably handle the jpg→png fallback automatically when it isn't available.

**Comment by Tyler-2** [comment]
Is this not the right way to do that?
`java -DimageFormat=png -jar Downloads/adb-remote-control.jar`

Bit of a java nub.

**Comment by oberien** [comment]
You need to configure it in a config file as described here: <https://github.com/oberien/adb-remote-control#config>

**Comment by retani** [comment]
Create a file named `config.properties` in the same folder in which you run `java -jar adb-remote-control`. Place 1 line in it:
````
imageFormat = png
````
That's it. I had the issue on Mac.

**Comment by oberien** [comment]
Thanks for the description of creating the config file. As you are confirming that this fixes the problem on your end, I'm closing this issue for now.

**Comment by ghost** [comment]
Hello, I found this tool and i find it very useful!
At first i had the same Problem, then i added `imageFormat=png` to the `config.properties` and it worked (at least for a minute).
Then it began thowing the same error.
the commands `adb exec-out screencap -p > screen.png` and `adb exec-out screencap -p > screen.png` are successfully making screenshots and putting the data into a file that is readable for my photo-viewer.
I'm currently using Linux Mint (Mate desktop environment):
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=uma
DISTRIB_DESCRIPTION="Linux Mint 20.2 Uma"
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal
```
i'm executing java with this command: java -jar adb-remote-control.jar

Do you have an idea what I'm doing wrong?

**Comment by ghost** [comment]
nevermind, I just saw the link to the other issue XD
