### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ogmkp** [oberien/adb-remote-control#15]
Hello, I have this result, and no more action, what I've missed ?

>$ java -jar adb-remote-control.jar 
> Config File not found, falling back to defaults
> Get Screenshot
> Switching to Base64-Mode
> Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 3a
> 	at java.base/java.util.Base64$Decoder.decode0(Base64.java:743)
> 	at java.base/java.util.Base64$Decoder.decode(Base64.java:591)
> 	at de.oberien.adbremotecontrol.adb.AdbScreencap.getScreenshot(AdbScreencap.java:34)
> 	at de.oberien.adbremotecontrol.adb.AdbDevice.screenshot(AdbDevice.java:37)
> 	at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:22)
> 	at de.oberien.adbremotecontrol.Main.main(Main.java:7)

Java version:
> $ java -version
> openjdk version "11.0.9.1" 2020-11-04
> OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
> OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

Device available:
> $ adb devices 
> List of devices attached
> GAAXGV141680PZJ	device

Thanks !

**Comment by oberien** [comment]
Could you try setting `imageFormat` to `png` in the config?

**Comment by ogmkp** [comment]
Setted to config.properties :
> imageFormat = png

Same errors.

**Comment by oberien** [comment]
Could you please follow the manual commands of trying to get a screenshot as described in https://github.com/oberien/adb-remote-control/issues/13#issuecomment-640399978?

**Comment by ogmkp** [comment]
Sure:
$ adb shell screencap -p 
[result.txt](https://github.com/oberien/adb-remote-control/files/5699079/result.txt)

```
$ adb shell screencap -p test.png
Error opening file: test.png (Read-only file system)
```


And -j don't exist:

```
$ adb shell screencap -j
screencap: invalid option -- j
usage: screencap [-hp] [-d display-id] [FILENAME]
   -h: this message
   -p: save the file as a png.
   -d: specify the display id to capture, default 0.
If FILENAME ends with .png it will be saved as a png.
If FILENAME is not given, the results will be printed to stdout.
```

**Comment by oberien** [comment]
1. Which OS are you using?
2. Which shell are you executing the jar from?
3. Could you please provide the output of `adb shell screencap -p | base64 -w 0` as a txt file?
4. Your `result.txt` file is broken. It should be a PNG, but the conversion to txt somewhere corrupted the file (`libpng error: PNG file corrupted by ASCII conversion`).

**Comment by ogmkp** [comment]
I'm using Debian 10 stable with bash.
Yes, here the output of  the command you provided:
[result.txt](https://github.com/oberien/adb-remote-control/files/5705538/result.txt)

Yes, I piped the command result in a straight file (adb shell screencap -p >> result.txt) and I dont understand why the file is weird.

**Comment by oberien** [comment]
The problem is that for some reason the png you're getting is output as text file with `\r\n` line endings. So every byte 0x10 is preceded by 0x13, as all line endings are converted from `\n` to `\r\n`. So far this only happened on Windows, and to me it doesn't make any sense for why it would happen on Linux. The interesting thing is that this even happens within the PNG when using base64 encoding, which feels super weird.

I'm sorry, but at this point I don't know how to fix this. It's not possible to easily automatically detect when this is happening so I can't just always convert line endings back in the PNG.

**Comment by ogmkp** [comment]
OK, this is, probably, a Android/ADB problem.
I'm using https://github.com/MajeurAndroid/java-adb-remote-screen instead.
But I suggest to you to evolve this method for video encoding like:

> $ adb exec-out screenrecord --output-format=h264 - | ffplay -probesize 32 -sync video  -


and adding adb to wakeup screen:

> $ adb shell input keyevent KEYCODE_POWER

In my case, I need to control remote my phone on USB and IP.
Good luck and thank you.

**Comment by mangust404** [comment]
Same issue on Ubuntu 18.04.4 LTS

adb: Android Debug Bridge version 1.0.41
Version 30.0.5-6877874

java: openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

**Comment by AR2000AR** [comment]
Same problem on debian 10
```
Config File not found, falling back to defaults
Get Screenshot
Switching to Base64-Mode
Exception in thread "main" java.lang.RuntimeException: Invalid image, but we are already using base64
	at de.oberien.adbremotecontrol.adb.AdbDevice.screenshot(AdbDevice.java:39)
	at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:22)
	at de.oberien.adbremotecontrol.Main.main(Main.java:7)
```

**Comment by bugeaud** [comment]
Same issue on Windows 10 with latest (to date) Android Debug Bridge version 1.0.41 Version 31.0.2-7242960

java-adb-remote-screen as suggested by @maxdrfr worked juste fine out of the box 👍

**Comment by SwimmingTiger** [comment]
> The problem is that for some reason the png you're getting is output as text file with `\r\n` line endings. So every byte 0x10 is preceded by 0x13, as all line endings are converted from `\n` to `\r\n`.

Use this (binary safe):
```
adb exec-out screencap -p
```

Not this (binary unsafe, `\n` may be converted to `\r\n` by `adb`):
```
adb shell screencap -p
```

---

```
adb shell screencap -p | base64 -w 0
```

> that this even happens within the PNG when using base64 encoding.

It will of course have `\r` because `adb shell` adds `\r`, and `base64` encoding happens after receiving something with `\r`.

If stdout is not binary safe, you might want this (`base64 -w 0` is not supported on android):
```
adb shell "screencap -p | base64"
adb exec-out "screencap -p | base64"
```

**Comment by ogmkp** [comment]
This project seems to be dead, so I'm closing this issue.
