### ISSUE TITLE
Broken running with java 9.0.4

### ISSUE THREAD

**Issue by sichmuehe** [oberien/adb-remote-control#2]
Look at the screenshot please
![image](https://user-images.githubusercontent.com/39306121/50376943-6a5feb00-061d-11e9-8d08-05444ad43cad.png)

**Comment by oberien** [comment]
Adb piping doesn't seem to work as before anymore. I added a hack which should make it work somewhat now, albeit Ctrl+d is buggy now. Could you please try again with [v0.1.2](https://github.com/oberien/adb-remote-control/releases/tag/v0.1.2) ?

**Comment by micer** [comment]
Hey there, I just had the same issue as https://github.com/oberien/adb-remote-control/issues/1 (no exception shown in terminal as here on the screenshot above), v0.1.2 works well for me tho. I'm using OnePlus 5. Let me know if you need some futher help with debugging or testing. And thanks for cool project!

**Comment by oberien** [comment]
If it works for you, I guess I can close this issue until someone else complains :)
