### ISSUE TITLE
phototan does not work remotely

### ISSUE THREAD

**Issue by Sur3** [oberien/adb-remote-control#8]
Hi I have a problem that I can not use my phototan app via remote control, there is just a white screen an errors, i read a similar problem was solvable for the signal messenger app, but sadly the documentation about that solution seems gone?

**Comment by oberien** [comment]
Thanks for the hint about the broken link in the readme, I fixed it.

My guess is that phototan simply disallows taking screenshots of the app. Signal has an option in its settings where you can enable screenshots. You could try searching if something similar exists for phototan.

**Comment by Sur3** [comment]
Ok atm i can not test that bc my display is broken, that's why I'm using the remote control, maybe I should try a MHL cable to see the screen, but i would still need remote control for inputs, and I think inputs via remote-control are also broken, because it throws errors for no screenshots coming back..

**Comment by Sur3** [comment]
Ok I got screenshots working for secured apps now using this secure flag patch: https://forum.xda-developers.com/apps/magisk/module-smali-patcher-0-7-t3680053
But it was quite complicated; I wonder if just having root privileges on adb would have circumvented the secure flag as well.
